name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: npm publish / GitHub release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_AUTHOR_NAME: 'A simple bot'
          GIT_AUTHOR_EMAIL: 'simplesaurus@evanlucas.com'
          GIT_COMMITTER_NAME: 'A simple bot'
          GIT_COMMITTER_EMAIL: 'simplesaurus@evanlucas.com'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@15 --debug
